from typing import Callable, Any

class ConfigType:  # L:41
    def __init__(self, func_obj: Callable[..., Any]): ...

class ConfigSection:  # L:211
    def __contains__(self, name: str) -> None: ...
    def keys(self) -> None: ...
    # def render_value(self, central, name, arg_type): ...
